#!/usr/bin/env bash
# ============================================================
# eMMA Setup Script
# ============================================================
# Automatische Einrichtung der Entwicklungs- oder Produktionsumgebung
# Usage: ./setup.sh [dev|prod]
# ============================================================

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging functions
log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check for required tools
check_dependencies() {
    log_info "Checking dependencies..."
    
    local missing=()
    
    command -v docker >/dev/null 2>&1 || missing+=("docker")
    command -v docker-compose >/dev/null 2>&1 || command -v "docker compose" >/dev/null 2>&1 || missing+=("docker-compose")
    command -v openssl >/dev/null 2>&1 || missing+=("openssl")
    
    if [ ${#missing[@]} -ne 0 ]; then
        log_error "Missing required tools: ${missing[*]}"
        log_info "Please install the missing tools and try again."
        exit 1
    fi
    
    log_success "All dependencies found"
}

# Generate cryptographic keys
generate_keys() {
    log_info "Generating cryptographic keys..."
    
    local secrets_dir="./secrets"
    mkdir -p "$secrets_dir"
    
    # JWT Signing Key (RSA 2048)
    if [ ! -f "$secrets_dir/config-signing.pem" ]; then
        openssl genrsa -out "$secrets_dir/config-signing.pem" 2048
        openssl rsa -in "$secrets_dir/config-signing.pem" -pubout -out "$secrets_dir/config-signing.pub.pem"
        chmod 600 "$secrets_dir/config-signing.pem"
        chmod 644 "$secrets_dir/config-signing.pub.pem"
        log_success "Generated JWT signing keys"
    else
        log_warn "JWT signing keys already exist, skipping"
    fi
    
    # Application Secret Key
    if [ ! -f "$secrets_dir/secret_key" ]; then
        openssl rand -hex 32 > "$secrets_dir/secret_key"
        chmod 600 "$secrets_dir/secret_key"
        log_success "Generated application secret key"
    else
        log_warn "Application secret key already exists, skipping"
    fi
    
    # Database Password
    if [ ! -f "$secrets_dir/db_password" ]; then
        openssl rand -base64 24 | tr -d '/+=' > "$secrets_dir/db_password"
        chmod 600 "$secrets_dir/db_password"
        log_success "Generated database password"
    else
        log_warn "Database password already exists, skipping"
    fi
}

# Create environment file
create_env_file() {
    local env_mode="${1:-dev}"
    
    log_info "Creating .env file for $env_mode environment..."
    
    if [ -f ".env" ]; then
        log_warn ".env file already exists. Creating .env.new instead"
        local env_file=".env.new"
    else
        local env_file=".env"
    fi
    
    local secret_key
    local db_password
    
    secret_key=$(cat ./secrets/secret_key)
    db_password=$(cat ./secrets/db_password)
    
    if [ "$env_mode" == "prod" ]; then
        cat > "$env_file" << EOF
# eMMA Production Configuration
# Generated by setup.sh on $(date -Iseconds)

ENVIRONMENT=production
DEBUG=false

# Database
DB_PASSWORD=${db_password}

# Security
SECRET_KEY=${secret_key}
ALLOWED_ORIGINS=https://emma.dojaflow.ai
ALLOWED_HOSTS=emma.dojaflow.ai,api.emma.dojaflow.ai

# Rate Limiting
RATE_LIMIT_REQUESTS_PER_MINUTE=60
RATE_LIMIT_BURST=10

# Agent Provisioning
AGENT_BINARY_BASE_URL=https://downloads.emma.dojaflow.ai
CONFIG_SIGNING_KEY_ID=emma-config-v1

# Logging
LOG_LEVEL=INFO
LOG_FORMAT=json
EOF
    else
        cat > "$env_file" << EOF
# eMMA Development Configuration
# Generated by setup.sh on $(date -Iseconds)

ENVIRONMENT=development
DEBUG=true

# Database
DB_PASSWORD=${db_password}

# Security
SECRET_KEY=${secret_key}
ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173

# Agent Provisioning
AGENT_BINARY_BASE_URL=http://localhost:8000
CONFIG_SIGNING_KEY_ID=emma-config-dev

# Logging
LOG_LEVEL=DEBUG
LOG_FORMAT=console
EOF
    fi
    
    log_success "Created $env_file"
}

# Initialize database
init_database() {
    log_info "Starting database and running migrations..."
    
    # Start only postgres first
    docker compose up -d postgres
    
    # Wait for postgres to be ready
    log_info "Waiting for PostgreSQL to be ready..."
    local max_attempts=30
    local attempt=0
    
    while [ $attempt -lt $max_attempts ]; do
        if docker compose exec -T postgres pg_isready -U emma -d emma >/dev/null 2>&1; then
            log_success "PostgreSQL is ready"
            break
        fi
        attempt=$((attempt + 1))
        sleep 1
    done
    
    if [ $attempt -eq $max_attempts ]; then
        log_error "PostgreSQL failed to start"
        exit 1
    fi
    
    # Run migrations
    log_info "Running database migrations..."
    docker compose run --rm migrations
    log_success "Database migrations completed"
}

# Start services
start_services() {
    log_info "Starting all services..."
    docker compose up -d
    
    log_info "Waiting for API to be ready..."
    local max_attempts=30
    local attempt=0
    
    while [ $attempt -lt $max_attempts ]; do
        if curl -sf http://localhost:8000/health >/dev/null 2>&1; then
            log_success "API is ready"
            break
        fi
        attempt=$((attempt + 1))
        sleep 2
    done
    
    if [ $attempt -eq $max_attempts ]; then
        log_warn "API health check timed out, but services may still be starting"
    fi
}

# Print status and next steps
print_status() {
    echo ""
    echo "============================================================"
    echo -e "${GREEN}eMMA Setup Complete!${NC}"
    echo "============================================================"
    echo ""
    echo "Services running:"
    docker compose ps --format "table {{.Name}}\t{{.Status}}\t{{.Ports}}"
    echo ""
    echo "Quick commands:"
    echo "  View logs:        docker compose logs -f api"
    echo "  Stop services:    docker compose down"
    echo "  Restart:          docker compose restart"
    echo "  Run tests:        docker compose exec api pytest"
    echo ""
    echo "API endpoints:"
    echo "  Health check:     http://localhost:8000/health"
    echo "  API docs:         http://localhost:8000/docs"
    echo "  OpenAPI spec:     http://localhost:8000/openapi.json"
    echo ""
    echo "============================================================"
}

# Main execution
main() {
    local env_mode="${1:-dev}"
    
    echo ""
    echo "============================================================"
    echo "eMMA Setup Script"
    echo "Mode: $env_mode"
    echo "============================================================"
    echo ""
    
    check_dependencies
    generate_keys
    create_env_file "$env_mode"
    init_database
    start_services
    print_status
}

# Show help
if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    echo "Usage: $0 [dev|prod]"
    echo ""
    echo "Options:"
    echo "  dev   Setup development environment (default)"
    echo "  prod  Setup production environment"
    exit 0
fi

main "${1:-dev}"
